version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - PORT=3300
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - POSTGRES_PASSWORD=postgres      
    ports:
      - 3300:3300
    depends_on:
      - postgres
    links:
      - postgres:postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev

  postgres:
    image: postgres:alpine
    restart: always
    environment:
      - DB_USER=postgres
      - DB_PASS=postgres
      - POSTGRES_HOST_AUTH_METHOD="trust"


  adminer:
    image: adminer
    restart: always
    ports:
        - 8080:8080